version: '3.8'

services:
  app:
    image: samuel910/municipalidad-app:latest
    container_name: municipalidad_app
    ports:
      # Expone la aplicación en el puerto web por defecto (80)
      - "80:5000"
    environment:
      # IP Pública de tu base de datos MySQL
      - DB_HOST=190.187.82.246
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=patrigest
    restart: unless-stopped
